/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface-variant': '#404943',
        'surface-bright': '#fff8f6',
        'surface-container-high': '#ffe2db',
        'surface-container': '#ffe9e4',
        'surface-variant': '#fadcd5',
        'inverse-surface': '#3e2c28',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'on-primary': '#ffffff',
        'primary-fixed-dim': '#99d3b1',
        'on-tertiary-fixed-variant': '#3f4949',
        'on-tertiary-container': '#a6b0b0',
        surface: '#fff8f6',
        'tertiary-fixed': '#dae4e4',
        primary: '#00331e',
        'on-primary-container': '#80ba99',
        'surface-container-lowest': '#ffffff',
        'inverse-primary': '#99d3b1',
        'on-secondary-fixed-variant': '#00522b',
        'on-tertiary-fixed': '#141d1e',
        'surface-container-low': '#fff1ed',
        'on-surface': '#271814',
        'surface-tint': '#31694c',
        'primary-fixed': '#b4f0cc',
        'inverse-on-surface': '#ffede9',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#3a4344',
        'on-primary-fixed': '#002112',
        'surface-container-highest': '#fadcd5',
        'surface-dim': '#f1d4cd',
        'secondary-fixed': '#98f7b5',
        'secondary-fixed-dim': '#7cda9b',
        'error-container': '#ffdad6',
        secondary: '#006d3b',
        'outline-variant': '#c0c9c1',
        'secondary-container': '#98f7b5',
        'on-secondary': '#ffffff',
        outline: '#707972',
        'on-secondary-fixed': '#00210e',
        'on-secondary-container': '#01743f',
        'primary-container': '#0e4b31',
        'tertiary-fixed-dim': '#bec8c8',
        'on-primary-fixed-variant': '#165036',
        background: '#fff8f6',
        'on-background': '#271814',
        tertiary: '#242d2d',
        error: '#ba1a1a',
      },
      borderRadius: {
        '2xl': '1.5rem',
      },
      spacing: {
        xs: '4px',
        lg: '48px',
        'margin-mobile': '16px',
        base: '8px',
        xl: '80px',
        'margin-desktop': '64px',
        md: '24px',
        sm: '12px',
        gutter: '20px',
      },
      fontFamily: {
        'body-md': ['Be Vietnam Pro', 'sans-serif'],
        'headline-md': ['Lexend', 'sans-serif'],
        'display-lg': ['Lexend', 'sans-serif'],
        'display-lg-mobile': ['Lexend', 'sans-serif'],
        'headline-sm': ['Lexend', 'sans-serif'],
        'label-sm': ['Be Vietnam Pro', 'sans-serif'],
        'body-lg': ['Be Vietnam Pro', 'sans-serif'],
        'label-md': ['Be Vietnam Pro', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
